# Generated by Django 4.1.2 on 2023-01-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalstate',
            name='type',
            field=models.CharField(max_length=40),
        ),
    ]
