# Generated by Django 4.1.2 on 2023-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0002_alter_chemicalstate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='molarity',
            field=models.FloatField(blank=True),
        ),
    ]
