# Generated by Django 4.1.2 on 2023-01-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0005_alter_bottle_molarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='molar_mass',
            field=models.FloatField(default=59.0917),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalstate',
            name='min_thresh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalstate',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
