# Generated by Django 4.1.2 on 2023-01-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0006_chemical_molar_mass_alter_chemicalstate_min_thresh_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bottle',
            new_name='Container',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='bottle',
            new_name='container',
        ),
    ]
