# Generated by Django 4.1.2 on 2023-01-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0007_rename_bottle_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='new',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('T', 'TRANSACT'), ('N', 'NEW'), ('R', 'RESET')], default='T', max_length=1),
        ),
    ]
