# Generated by Django 4.1.2 on 2023-02-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0008_remove_transaction_new_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('T', 'TRANSACT'), ('N', 'NEW'), ('R', 'RESET'), ('I', 'IGNORED')], default='T', max_length=1),
        ),
    ]
