# Generated by Django 4.1.2 on 2023-02-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='barcode',
        ),
    ]
