# Generated by Django 4.1.4 on 2023-09-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0012_transaction_user_transactionedit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='dangerous',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='molar_mass',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='safety',
            field=models.TextField(default='', null=True),
        ),
    ]
