# Generated by Django 4.1.2 on 2023-11-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0013_chemical_dangerous_alter_chemical_molar_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('T', 'TRANSACT'), ('N', 'NEW'), ('I', 'IGNORED')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='transactionedit',
            name='new_type',
            field=models.CharField(choices=[('T', 'TRANSACT'), ('N', 'NEW'), ('I', 'IGNORED')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transactionedit',
            name='old_type',
            field=models.CharField(choices=[('T', 'TRANSACT'), ('N', 'NEW'), ('I', 'IGNORED')], max_length=1),
        ),
    ]
