# Generated by Django 4.1.2 on 2023-11-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemlogs', '0014_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionEdit',
        ),
    ]
